apiVersion: v1
kind: Service
metadata:
    name: caddy-service
    namespace: caddy
spec:
    type: LoadBalancer
    selector:
        app: caddy
    ports:
        - name: http
          port: 80
          targetPort: 80
        - name: https
          port: 443
          targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: caddy-deployment
    namespace: caddy
spec:
    replicas: {{.Values.replicaCount}}
    selector:
        matchLabels:
            app: caddy
    template:
        metadata:
            name: caddy-pod
            labels:
                app: caddy
        spec:
            containers:
                - name: tls-check-container
                  image: ho0on/tls-check
                  ports:
                      - containerPort: 5555
                - name: caddy-container
                  image: ho0on/caddy
                  ports:
                      - name: http
                        containerPort: 80
                      - name: https
                        containerPort: 443
                  resources:
                      limits:
                          cpu: 1000m
                          memory: 2Gi
                      requests:
                          cpu: 100m
                          memory: 64Mi
                  volumeMounts:
                      - name: empty-dir
                        mountPath: /data
                      - name: empty-dir
                        mountPath: /config
            volumes:
                - name: empty-dir
                  emptyDir: {}
